
name: Deployment1

on:
  push:
    branches: [development , testing]
jobs:
  
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: sudo npm install --force

      - name: Buid the application
        run: npm run build:dev
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.ATL2_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.ATL2_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.ATL2_HOSTNAME }}:/tmp/aim_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.ATL2_HOSTNAME }} '
            sudo rm -rf /var/www/html/aim_fe/build &&
            sudo mv /tmp/aim_fe_build /var/www/html/aim_fe/build &&
            cd /var/www/html/aim_fe &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development
      - name: Deploy to Development
        if: github.ref == 'refs/heads/testing'
        env:
          PRIVATE_KEY: ${{ secrets.ATL2_STG_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.ATL2_STG_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.ATL2_STG_HOSTNAME }}:/tmp/aim_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.ATL2_HOSTNAME }} '
            sudo rm -rf /var/www/html/aim_fe/build &&
            sudo mv /tmp/aim_fe_build /var/www/html/aim_fe/build &&
            cd /var/www/html/aim_fe &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development
        
            '

            

      
  
